name: Generate cheats.rs static files

on:
  push:
  schedule:
    - cron: '0 2 * * *'

env:
  REPO_URL: https://github.com/ralfbiedert/cheats.rs
  REPO_BRANCH: master
  MY_SECRET: ${{secrets.commit_secret}}
  RUST_BACKTRACE: 1

jobs:
  runner:
    name: 'Generate cheats.rs static files'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: Initialization environment
        run: |
          wget -q -O - "https://github.com/getzola/zola/releases/download/v0.15.0/zola-v0.15.0-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
        
      - name: Clone source code
        working-directory: /workdir
        run: |
          git clone $REPO_URL -b $REPO_BRANCH cheats.rs
          ln -sf /workdir/cheats.rs $GITHUB_WORKSPACE/cheats.rs
          
      - name: build static
        run: cd cheats.rs && zola build && ls -alh ./public/

